name: Build Docker

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKER_HUB_PW }}" | docker login -u masterkia --password-stdin
        docker image build -t masterkia/koko .
        docker push masterkia/koko
